spring:
  main:
    web-application-type: none
  config:
    import: "optional:configtree:/mnt/secrets/hmc/"
  application:
    name: Operational Reports Runner
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  datasource:
    hikari:
      data-source-properties: stringtype=unspecified
    tomcat:
      connection-properties: stringtype=unspecified
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${CFT_HEARING_SERVICE_DB_HOST:localhost}:${CFT_HEARING_SERVICE_DB_PORT:5060}/${CFT_HEARING_SERVICE_DB_NAME:hmc_cft_hearing_service}${CFT_HEARING_SERVICE_DB_OPTIONS:}
    username: ${CFT_HEARING_SERVICE_DB_USERNAME:hmc}
    password: ${CFT_HEARING_SERVICE_DB_PASSWORD:hmc}
    type: com.zaxxer.hikari.HikariDataSource
  flyway:
    out-of-order: true
    ignore-missing-migrations: true

#application-insights:
#  default:
#    modules:
#      WebSyntheticRequestTelemetryInitializer:
#        enabled: false
#
#azure:
#  application-insights:
#    instrumentation-key: ${APPINSIGHTS_INSTRUMENTATIONKEY:00000000-0000-0000-0000-000000000000}

smoke.test.enabled: false

app.insights.log.size: ${OPERATIONAL_REPORTS_RUNNER_LOG_SIZE:250}
