server:
  port:

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

springdoc:
  packagesToScan: uk.gov.hmcts.reform.reports.controllers

#If you use a database then uncomment below lines and update db properties accordingly
spring:
  config:
    import: "optional:configtree:/mnt/secrets/hmc/"
  application:
    name: HMC Operational Reports Runner
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}${DB_OPTIONS:}
#    username: ${DB_USER_NAME}
#    password: ${DB_PASSWORD}
#    properties:
#      charSet: UTF-8
#    hikari:
#      minimumIdle: 2
#      maximumPoolSize: 10
#      idleTimeout: 10000
#      poolName: {to-be-defined}HikariCP
#      maxLifetime: 7200000
#      connectionTimeout: 30000
#  jpa:
#    properties:
#      hibernate:
#        jdbc:
#          lob:
#            # silence the 'wall-of-text' - unnecessary exception throw about blob types
#            non_contextual_creation: true

notify:
  api-key: ${NOTIFY_HMC_API_KEY:notify-gov-api-key}
  email-templates:
      error-template-id: ${NOTIFY_EMAIL_ERROR_TEMPLATE_ID:a60215dd-08bb-475e-956c-e97fdb7e448c}
      awaiting-hearings-template-id: ${NOTIFY_EMAIL_AWAITING_ACTUALS_TEMPLATE_ID:a60215dd-08bb-475e-956c-e97fdb7e448c}
  email-addresses:
    error-email-address: ${NOTIFY_EMAIL_ERROR_ADDRESS}
    awaiting-hearings-email-address: ${NOTIFY_EMAIL_AWAITING_ACTUALS_ADDRESS}

azure:
  application-insights:
    web.enabled: false
    instrumentation-key: ${hmc.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}

smoke.test.enabled: false
