server:
  port:

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

spring:
  config:
    import: "optional:configtree:/mnt/secrets/hmc/"
  application:
    name: HMC Operational Reports Runner
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:11:///databasename?stringtype=unspecified
  jpa:
    hibernate:
      ddl-auto: create
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: http://localhost:${wiremock.server.port:5000}/o
ccd:
  data-store:
    host: http://localhost:${wiremock.server.port:4452}
idam:
  api:
    url: http://localhost:${wiremock.server.port:5000}
  s2s-auth:
    url: http://localhost:${wiremock.server.port:5000}/s2s


app.configuredNumberOfDays: 2

