java:
  image: 'https://hmctspublic.azurecr.io/hmc/hmc-operational-reports-runner:latest'
  kind: CronJob
  schedule: "0 01 02 ? * * *"
  startingDeadlineSeconds: 600
  concurrencyPolicy: Forbid
  ingressHost: hmc-operational-reports-runner-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: hmc
  #  Uncomment once the vault containing the app insights key has been set up
  keyVaults:
    hmc:
      secrets:
        - name: AppInsightsInstrumentationKey
          alias: azure.application-insights.instrumentation-key
        - name: notify-hmc-api-key
          alias: NOTIFY_HMC_API_KEY
        - name: notify-error-template-id
          alias: NOTIFY_ERROR_TEMPLATE_ID
        - name: notify-error-email-address
          alias: NOTIFY_ERROR_EMAIL_ADDRESS
        - name: notify-error-reply-to-email-address
          alias: NOTIFY_ERROR_REPLY_TO_EMAIL_ADDRESS
        - name: notify-awaiting-actuals-template-id
          alias: NOTIFY_AWAITING_ACTUALS_TEMPLATE_ID
        - name: notify-awaiting-actuals-email-address
          alias: NOTIFY_AWAITING_ACTUALS_EMAIL_ADDRESS
        - name: notify-awaiting-actuals-reply-to-email-address
          alias: NOTIFY_AWAITING_ACTUALS_REPLY_TO_EMAIL_ADDRESS
  environment:
  #    TODO
  global:
    jobKind: CronJob
