java:
  image: 'https://hmctspublic.azurecr.io/hmc/hmc-operational-reports-runner:latest'
  kind: CronJob
  schedule: "0 01 02 ? * * *"
  startingDeadlineSeconds: 600
  concurrencyPolicy: Forbid
  ingressHost: hmc-operational-reports-runner-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: hmc
  #  Uncomment once the vault containing the app insights key has been set up
  keyVaults:
    hmc:
      secrets:
        - name: AppInsightsInstrumentationKey
          alias: azure.application-insights.instrumentation-key
        - name: notify-hmc-api-key
          alias: NOTIFY_HMC_API_KEY
        - name: notify-email-error-template-id
          alias: NOTIFY_EMAIL_ERROR_TEMPLATE_ID
        - name: notify-email-awaiting-actuals-template-id
          alias: NOTIFY_EMAIL_AWAITING_ACTUALS_TEMPLATE_ID
        - name: notify-email-error-address
          alias: NOTIFY_EMAIL_ERROR_ADDRESS
        - name: notify-email-address-actuals-address
          alias: NOTIFY_EMAIL_AWAITING_ACTUALS_ADDRESS
  environment:
  #    TODO
  global:
    jobKind: CronJob
